name: flask_application

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"
    volumes:
      - pdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  pdata: